export const selectData = {
  estate: {
    listing: ["Buying", "Renting", "Selling"],
    property: [
      "House",
      "Condominium",
      "Apartment/Flat",
      "Commericial",
      "Farmhouse",
      "Land",
      "Industrial",
      "Room",
      "Other",
    ],
    bedrooms: ["1", "2", "3", "4", "5+", "None"],
    bathrooms: ["1", "2", "3", "4", "5+", "None"],
    tenure: ["Freehold", "Leasehold", "Unknown"],
    propertyCondition: ["Excellent", "Good", "In need of repair"],
    key: [
      "Detached property",
      "Garage",
      "Double garage",
      "Private garden",
      "Communal garden",
      "Open plan living",
      "Gated community",
      "Balcony",
    ],
    nearest: [
      "Primary school",
      "Secondary school",
      "University",
      "Hospital",
      "Public transport",
      "Airport",
      "Restaurants & cafes",
      "Shopping centre",
      "Public park",
      "Beach",
      "None",
    ],
    facilities: [
      "Private parking",
      "Off road parking",
      "Internet",
      "Pets allowed",
      "Room service",
      "Shower",
      "Smoke alarms",
      "Fire extinguishers",
      "Washing machine",
      "Dishwasher",
      "Microwave",
      "Refrigerator",
      "Kitchenware",
      "Oven",
      "Dining area",
      "Seating Area",
      "Private entrance",
      "Heating",
      "Air conditioning",
      "Built-in wardrobes",
      "Fitten kitchen",
      "Disabled person facilities",
      "Private swimming pool",
      "Communal swimming pool",
      "Games Room",
      "Underfloor heating",
    ],
  },
};
